In [4]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import  LabelBinarizer
from sklearn_pandas import DataFrameMapper
from sklearn.base import TransformerMixin

In [5]:
raw_data = pd.read_csv('inputfile.csv', encoding= 'latin-1 ')
raw_data["width"]= raw_data.width.str.replace('+', '')
features = ['price', 'numshows', 'width','medium', 'instit']
df = raw_data[features]
df = df.iloc[:1000,:]

AttributeError: 'DataFrame' object has no attribute 'width'

In [6]:
raw_data = pd.read_csv('inputfile.csv', encoding= 'latin-1 ')
raw_data

,Unnamed: 0,artist,years_active,numshows,instit,artwork,price,dimension,medium,dim
0,0,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",jam_rasberry,37000,1;12,painting,1
1,2,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",flowers,49000,1;12,painting,1
2,3,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",gemini,39000,13;30,painting,13
3,5,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",volkswagen,49000,13;30,painting,13
4,6,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",lenin,49000,13;30,painting,13
5,8,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",uncle_sam,29000,31+,painting,31+
6,10,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",electric_chair,39000,31+,painting,31+
7,12,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",sarah_goldsmith,49000,31+,painting,31+
8,13,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",portrait_of_a_society_lady,49000,31+,painting,31+
9,14,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",grace_kelly_fs_ii305,49000,31+,painting,31+
10,15,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",paramount_ii352,49000,31+,painting,31+
11,16,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",mickey_mouse,49000,31+,painting,31+
12,17,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",wilhelmina_ross_from_ladies_and_gentleman,49000,31+,painting,31+
13,18,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",portrait_of_john_richardson,49000,31+,painting,31+
14,19,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",superman,49000,31+,painting,31+
15,20,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",star,49000,31+,painting,31+
16,21,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",jagger_10_promo_minicards_leo_castelli_graphic...,1000,1;12,prints_multiples,1
17,22,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",andy_warhol_velvet_underground_nico_unpeeled_b...,1000,1;12,prints_multiples,1
18,23,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",america_2editions_signed_heart_drawing,1000,1;12,prints_multiples,1
19,24,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",marilyn_monroe,1000,1;12,prints_multiples,1
20,27,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",dracula,2000,1;12,prints_multiples,1
21,28,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",trucks_announcement,2000,1;12,prints_multiples,1
22,29,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",santa_claus,3000,1;12,prints_multiples,1
23,30,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",man_ray,3000,1;12,prints_multiples,1
24,32,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",halston_from_andy_warhols_portraits_of_the_70s...,3000,1;12,prints_multiples,1
25,33,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",25_cats_named_sam_and_one_blue_pussy_iv65,3000,1;12,prints_multiples,1
26,34,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",25_cats_named_sam_and_one_blue_pussy_iv52,3000,1;12,prints_multiples,1
27,35,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",25_cats_named_sam_and_one_blue_pussy_iv67,3000,1;12,prints_multiples,1
28,36,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",in_the_bottom_of_my_garden_103a,4000,1;12,prints_multiples,1
29,37,andy_warhol,1928.0,3971,"[the_andy_warhol_museum, art_gallery_of_albert...",in_the_bottom_of_my_garden_99a,4000,1;12,prints_multiples,1
...,...,...,...,...,...,...,...,...,...,...
91386,191213,eugene_james_martin,NaN,3,"[beta_pictoris_gallery_maus_contemporary, masu...",food_and_drugs,19000,31+,painting,31+
91387,191233,eugene_james_martin,NaN,3,"[beta_pictoris_gallery_maus_contemporary, masu...",human_sponge,2000,1;12,works_on_paper,1
91388,191238,j_clayton_bright,NaN,1,[brecks_mill],the_blue_vase,2000,1;12,painting,1
91389,191239,clark_goolsby,NaN,1,[jaus],rainbow_variation_vi,1000,13;30,painting,13
91390,191240,clark_goolsby,NaN,1,[jaus],rainbow_variation_xi,1000,13;30,painting,13
91391,191241,clark_goolsby,NaN,1,[jaus],rainbow_variation_iv,1000,13;30,painting,13
91392,191242,clark_goolsby,NaN,1,[jaus],sidelong_glance,2000,13;30,painting,13
91393,191247,clark_goolsby,NaN,1,[jaus],charwill,3000,13;30,painting,13
91394,191248,clark_goolsby,NaN,1,[jaus],like_that,3000,13;30,painting,13
91395,191249,clark_goolsby,NaN,1,[jaus],second_attempt,3000,13;30,painting,13
91396,191250,clark_goolsby,NaN,1,[jaus],skull_iv,3000,31+,painting,31+
91397,191251,clark_goolsby,NaN,1,[jaus],tÃ­Ã¨te_de_cerf,3000,31+,painting,31+
91398,191252,clark_goolsby,NaN,1,[jaus],something_happened,4000,31+,painting,31+
91399,191253,clark_goolsby,NaN,1,[jaus],skull_v,4000,31+,painting,31+
91400,191257,clark_goolsby,NaN,1,[jaus],of_all_these_things,5000,31+,painting,31+
91401,191258,clark_goolsby,NaN,1,[jaus],positive_negative_diptych,6000,31+,painting,31+
91402,191259,clark_goolsby,NaN,1,[jaus],jumble,6000,31+,painting,31+
91403,191260,clark_goolsby,NaN,1,[jaus],this_that_the_other_then_some,6000,31+,painting,31+
91404,191262,clark_goolsby,NaN,1,[jaus],yesterday_this_all_seemed_new,8000,31+,painting,31+
91405,191263,clark_goolsby,NaN,1,[jaus],big_stack,11000,31+,painting,31+
91406,191265,clark_goolsby,NaN,1,[jaus],trouble,1000,13;30,works_on_paper,13
91407,191266,clark_goolsby,NaN,1,[jaus],frame_ii,1000,13;30,works_on_paper,13
91408,191267,clark_goolsby,NaN,1,[jaus],frame_i,1000,13;30,works_on_paper,13
91409,191268,clark_goolsby,NaN,1,[jaus],rainbow_piece_iii,2000,13;30,works_on_paper,13
91410,191271,camilla_tadich,1982.0,2,"[mars_melbourne_art_rooms, flinders_lane_gallery]",125am_muirs_road,1000,13;30,painting,13
91411,191272,camilla_tadich,1982.0,2,"[mars_melbourne_art_rooms, flinders_lane_gallery]",picnic,1000,13;30,painting,13
91412,191273,camilla_tadich,1982.0,2,"[mars_melbourne_art_rooms, flinders_lane_gallery]",wild_dog_creek,1000,13;30,painting,13
91413,191274,camilla_tadich,1982.0,2,"[mars_melbourne_art_rooms, flinders_lane_gallery]",beloved,1000,13;30,painting,13
91414,191275,camilla_tadich,1982.0,2,"[mars_melbourne_art_rooms, flinders_lane_gallery]",310am_jacksons_road,1000,13;30,painting,13
91415,191276,matthew_king,NaN,2,"[harpers_books, goodman_gallery_cape]",179_the_vanishing_american,1000,13;30,painting,13

In [17]:
features = ['price', 'numshows', 'width','medium', 'instit']
df = raw_data[features]
df = df.iloc[:1000,:]
df

KeyError: "['width'] not in index"

In [18]:
features = ['price', 'numshows', 'dimension','medium', 'instit']
df = raw_data[features]
df = df.iloc[:1000,:]
df

,price,numshows,dimension,medium,instit
0,37000,3971,1;12,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
1,49000,3971,1;12,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
2,39000,3971,13;30,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
3,49000,3971,13;30,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
4,49000,3971,13;30,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
5,29000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
6,39000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
7,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
8,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
9,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
10,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
11,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
12,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
13,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
14,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
15,49000,3971,31+,painting,"[the_andy_warhol_museum, art_gallery_of_albert..."
16,1000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
17,1000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
18,1000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
19,1000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
20,2000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
21,2000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
22,3000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
23,3000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
24,3000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
25,3000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
26,3000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
27,3000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
28,4000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
29,4000,3971,1;12,prints_multiples,"[the_andy_warhol_museum, art_gallery_of_albert..."
...,...,...,...,...,...
970,10000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
971,15000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
972,17000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
973,19000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
974,19000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
975,19000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
976,19000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
977,19000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
978,24000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
979,24000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
980,29000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
981,34000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
982,39000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
983,49000,1202,31+,prints_multiples,"[kunstmuseum_basel_|_gegenwart, kunstmuseum_ba..."
984,49000,1288,13;30,prints_multiples,"[da_mihi_gallery, san_francisco_museum_of_mode..."
985,49000,1288,13;30,works_on_paper,"[da_mihi_gallery, san_francisco_museum_of_mode..."
986,23000,602,1;12,prints_multiples,"[simon_lee_gallery_hong_kong, 303_gallery, co_..."
987,18000,602,1;12,works_on_paper,"[simon_lee_gallery_hong_kong, 303_gallery, co_..."
988,21000,602,1;12,works_on_paper,"[simon_lee_gallery_hong_kong, 303_gallery, co_..."
989,29000,602,1;12,works_on_paper,"[simon_lee_gallery_hong_kong, 303_gallery, co_..."
990,49000,876,1;12,painting,"[ota_fine_arts_singapore, artglorieux, hirshho..."
991,49000,876,31+,painting,"[ota_fine_arts_singapore, artglorieux, hirshho..."
992,1000,876,1;12,prints_multiples,"[ota_fine_arts_singapore, artglorieux, hirshho..."
993,1000,876,13;30,prints_multiples,"[ota_fine_arts_singapore, artglorieux, hirshho..."
994,32000,876,13;30,prints_multiples,"[ota_fine_arts_singapore, artglorieux, hirshho..."
995,26000,857,31+,photography,"[musÃ©e_dart_contemporain_de_montrÃ©al, pkm_ga..."
996,29000,857,13;30,works_on_paper,"[musÃ©e_dart_contemporain_de_montrÃ©al, pkm_ga..."
997,49000,578,31+,painting,"[kunstraum_innsbruck, museum_of_fine_arts_bost..."
998,49000,578,31+,painting,"[kunstraum_innsbruck, museum_of_fine_arts_bost..."
999,4000,578,1;12,prints_multiples,"[kunstraum_innsbruck, museum_of_fine_arts_bost..."

In [2]:
def model():
        # create model
        model = Sequential()
        model.add(Dense(54, input_dim=3006, kernel_initializer='normal', activation='relu'))
        model.add(Dense(9, kernel_initializer='normal', activation='relu'))
        model.add(Dense(2, kernel_initializer='normal', activation='relu'))
        model.add(Dense(1, kernel_initializer='normal'))
        # Compile model
        model.compile(loss='mean_squared_error', optimizer='adam')
        return model

In [3]:
class DenseTransformer(TransformerMixin):
    def transform(self, X, y=None, **fit_params):
        return X.todense()
    def fit_transform(self, X, y=None, **fit_params):
        self.fit(X, y, **fit_params)
        return self.transform(X)
    def fit(self, X, y=None, **fit_params):
        return self  


pipeline = Pipeline([
    ('mapper', DataFrameMapper([
                    #('artist', LabelBinarizer()),
                    ('numshows', None),
                    ('dimension', None),
                    ('medium', LabelBinarizer()),
                    ('instit', Pipeline([
                        ('instit', CountVectorizer(max_features = 3000)),
                        ('transformer', DenseTransformer())]))
                    ]))
])

NameError: name 'TransformerMixin' is not defined

In [4]:
X = pipeline.fit_transform(X1)
X.shape

NameError: name 'pipeline' is not defined

In [5]:
Y= df.price.values
X1= df[df.columns.drop(['price'])]

NameError: name 'df' is not defined

In [6]:
X = pipeline.fit_transform(X1)

NameError: name 'pipeline' is not defined

In [7]:
X

NameError: name 'X' is not defined

In [8]:
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)

NameError: name 'numpy' is not defined

In [9]:
seed = 7
np.random.seed(seed)
# evaluate model with standardized dataset
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)

NameError: name 'np' is not defined

In [10]:
pipeline

NameError: name 'pipeline' is not defined

In [11]:
estimators

NameError: name 'estimators' is not defined

In [12]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimator, X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [13]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimators, X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [14]:
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)

NameError: name 'numpy' is not defined

In [15]:
seed = 7
np.random.seed(seed)
# evaluate model with standardized dataset
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)

NameError: name 'np' is not defined

In [16]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimators, X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [17]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimator, X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [18]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimator[0], X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [19]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimators[0], X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [20]:
seed = 7
np.random.seed(seed)
# evaluate model with standardized dataset
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)

NameError: name 'np' is not defined

In [21]:
estimators[0]

NameError: name 'estimators' is not defined

In [22]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimator[0], X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [23]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimators[0], X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [24]:
kfold = KFold(n_splits=10, random_state=seed)

NameError: name 'KFold' is not defined

In [25]:
kfold

NameError: name 'kfold' is not defined

In [26]:
results = cross_val_score(lasso, X, Y, cv=kfold)

NameError: name 'cross_val_score' is not defined

In [27]:
lasso = linear_model.Lasso()

NameError: name 'linear_model' is not defined

In [28]:
scaler = StandardScaler()

NameError: name 'StandardScaler' is not defined

In [29]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(scaler, X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [30]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(scaler, X, Y)

NameError: name 'KFold' is not defined

In [31]:
pipeline

NameError: name 'pipeline' is not defined

In [32]:
results = cross_val_score(pipeline, X, Y, cv=kfold)

NameError: name 'cross_val_score' is not defined

In [33]:
pipeline[0]

NameError: name 'pipeline' is not defined

In [34]:
pipeline

NameError: name 'pipeline' is not defined

In [35]:
KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0))

SyntaxError: invalid syntax (<ipython-input-35-a388f527ef1b>, line 1)

In [36]:
KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0)

NameError: name 'KerasRegressor' is not defined

In [37]:
results = cross_val_score(KerasRegressor(build_fn=model, epochs=50, batch_size=5, verbose=0), X, Y, cv=kfold)

NameError: name 'cross_val_score' is not defined

In [38]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=100, batch_size=5, verbose=0)

NameError: name 'numpy' is not defined

In [39]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=model, nb_epoch=100, batch_size=5, verbose=0)

NameError: name 'np' is not defined

In [40]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=100, batch_size=5, verbose=0)

NameError: name 'numpy' is not defined

In [41]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=100, batch_size=5, verbose=0)

NameError: name 'np' is not defined

In [42]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=model, nb_epoch=100, batch_size=5, verbose=0)

NameError: name 'np' is not defined

In [43]:
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimator, X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

NameError: name 'KFold' is not defined

In [44]:
score = model.evaluate(X, Y,verbose=1)

print(score)

AttributeError: 'function' object has no attribute 'evaluate'

In [45]:
model = model()

NameError: name 'Sequential' is not defined